experiment: 'afhq256_3d'
phase: 'train'
cfg: 'afhq' 
data: 'data/AFHQ/afhq_v2_256.zip'
gpus: 8
batch: 32
decoder_output_dim: 32
g_module: 'training.dual_triplane.DualTriPlaneGenerator'
retidx: [-3, -1]
aware3d_res: [4,8,16,32,64,128,256]
d_module: 'training.dual_discriminator.DualDiscriminator'
d_patch_module: 'training.dual_discriminator.SingleDiscriminator'
triplane_resolution: 256
triplane_channels: 96
triplane_act: None
snap: 200
resume: '010000' #'eg3d/out/afhq256_2d/network-snapshot-001600.pkl'
patch_scale: 0.25
lpips: True
patch_gan: 0.2
aug: 'ada'
gamma: 5.0
gamma_patch: 5.0
density_reg_p_dist: 0.002

# inference
# metrics: []
chunk: -1
inference_mode: 'video'
image_mode: 'image'
seeds: [0, 4]
grid: (2, 2)
w_frames: 120
coarse: 0
neural_rendering_resolution_infer: 256
resize_resolution: 256
pitch_range: 0.25
yaw_range: 0.35
retplane: -1
