experiment: 'ffhq256_3d_train'
phase: 'train'
data: 'data/FFHQ/FFHQ_256.zip'
gpus: 8
batch: 32
decoder_output_dim: 32
g_module: 'training.dual_triplane.DualTriPlaneGenerator'
retidx: [-3, -1]
aware3d_res: [4,8,16,32,64,128,256]
d_module: 'training.dual_discriminator.DualDiscriminator'
d_patch_module: 'training.dual_discriminator.SingleDiscriminator'
triplane_resolution: 256
triplane_channels: 96
triplane_act: None
snap: 200
resume: None # '016200' | 'out/ffhq256_2d/network-snapshot-024000.pkl' | None
patch_scale: 0.25
lpips: True
patch_gan: 0.2
density_reg_p_dist: 0.002

# inference
# metrics: []
chunk: -1
inference_mode: 'video'
image_mode: 'image'
seeds: [0, 4]
grid: (2, 2)
w_frames: 120
coarse: 0
neural_rendering_resolution_infer: 256
resize_resolution: 256
pitch_range: 0.25 # 0.25
yaw_range: 0.35 # 0.35
retplane: 2
