experiment: 'shapenet128_3d'
phase: 'train'
cfg: 'shapenet'
data: 'data/ShapeNet/cars_128.zip'
gpus: 8
batch: 32
decoder_output_dim: 32
g_module: 'training.dual_triplane.DualTriPlaneGenerator'
retidx: [-3, -1]
aware3d_res: [4,8,16,32,64,128,256]
d_module: 'training.dual_discriminator.DualDiscriminator'
d_patch_module: 'training.dual_discriminator.SingleDiscriminator'
triplane_resolution: 256
triplane_channels: 96
triplane_act: None
snap: 200
resume: '013600' # 'eg3d/out/shapenet128_2d/network-snapshot-025000.pkl'
resume_kimg: 0
patch_scale: 0.5
lpips: True
feat_match: 0
detail_reg: 0
patch_gan: 0.2
accum_iter: 1
density_reg_p_dist: 0.002

# inference
# metrics: []
chunk: -1 # 131072
inference_mode: 'video'
image_mode: 'image'
seeds: [0, 4]
grid: (2, 2)
w_frames: 120
coarse: 0
neural_rendering_resolution_infer: 128
resize_resolution: 128
pitch_range: 0.25
yaw_range: 0.35
retplane: -1
