experiment: 'shapenet128_2d'
phase: 'train'
cfg: 'shapenet'
data: 'data/ShapeNet/cars_128.zip'
gpus: 8
batch: 32
decoder_output_dim: 32
d_module: 'training.dual_discriminator.DualDiscriminator'
aware3d_res: [4,8,16,32,64,128,256]
triplane_resolution: 256
triplane_channels: 96
triplane_act: None
snap: 200
resume: '025000'
resume_kimg: 0
patch_scale: 1.0

# inference
chunk: -1 # 131072
inference_mode: 'video'
image_mode: 'image'
seeds: [0, 4]
grid: (2, 2)
w_frames: 120
coarse: 1
neural_rendering_resolution_infer: 64
resize_resolution: 128
pitch_range: 0.25
yaw_range: 0.35
retplane: -1
shapes: False